// AUTO-GENERATED by scripts/build-layouts.mjs — do not edit by hand.
import type { FaceDef } from './layout-types';

export const GENERATED_FACES: Record<string, FaceDef[]> = {
  "azau": [
    {
      "id": "main",
      "widthPx": 141.73,
      "heightPx": 226.77,
      "widthMm": 50,
      "heightMm": 80,
      "layers": [
        {
          "kind": "image",
          "id": "deco6",
          "label": "Фон",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/azau-main-deco1.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "deco7",
          "label": "Графика 1",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/azau-main-deco2.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "text",
          "id": "t1",
          "text": "Оплата заказа.\nЧаевые. Отзыв.",
          "xf": 0.1782960558809003,
          "yf": 0.12285222913083742,
          "wf": 3,
          "fontSizeF": 0.09172369999294434,
          "align": "left",
          "fill": "#FFFFFF",
          "fontStyle": "bold",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t2",
          "text": "Оплатите заказ без официанта.\nЦеликом или только свою часть.",
          "xf": 0.14556480632187965,
          "yf": 0.26526260087313136,
          "wf": 3,
          "fontSizeF": 0.04938968461158541,
          "align": "left",
          "fill": "#FFFFFF",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t3",
          "text": "111222",
          "xf": 0.41673886968178936,
          "yf": 0.9211275741941173,
          "wf": 3,
          "fontSizeF": 0.04938968461158541,
          "align": "left",
          "fill": "#FFFFFF",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t4",
          "text": "01",
          "xf": 0.47086925844916394,
          "yf": 0.767787626229219,
          "wf": 3,
          "fontSizeF": 0.04938968461158541,
          "align": "left",
          "fill": "#FFFFFF",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "image",
          "id": "qr5",
          "label": "QR-код",
          "xf": 0.2800042334015382,
          "yf": 0.41448780702914845,
          "wf": 0.43992097650462153,
          "hf": 0.27494818538607396,
          "defaultSrc": "/layers/azau-main-qr.png",
          "opacity": 1
        }
      ]
    }
  ],
  "onix": [
    {
      "id": "main",
      "widthPx": 167.24,
      "heightPx": 158.74,
      "widthMm": 59,
      "heightMm": 56,
      "layers": [
        {
          "kind": "image",
          "id": "deco13",
          "label": "Диск (градиент)",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/onix-main-deco1.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "deco14",
          "label": "Основа",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/onix-main-deco2.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "text",
          "id": "t8",
          "text": "1234567",
          "xf": 0.20919397273379575,
          "yf": 0.6147121078493134,
          "wf": 3,
          "fontSizeF": 0.02391772303276728,
          "align": "left",
          "fill": "#B2B2B2",
          "fontStyle": "normal",
          "rotation": -90
        },
        {
          "kind": "text",
          "id": "t9",
          "text": "07",
          "xf": 0.7722381009327912,
          "yf": 0.5372338415018267,
          "wf": 3,
          "fontSizeF": 0.03587658454915092,
          "align": "left",
          "fill": "#B2B2B2",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "arc10",
          "text": "Оплата заказа. Чаевые. Отзыв.",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "fontSizeF": 0.07773259985649365,
          "align": "center",
          "fill": "#FFFFFF",
          "fontStyle": "bold",
          "rotation": 0,
          "arc": {
            "sweepDeg": 250
          }
        },
        {
          "kind": "text",
          "id": "t11",
          "text": "Всё в одном\nQR-коде",
          "xf": 0.3926464960535757,
          "yf": 0.20932531183066647,
          "wf": 3,
          "fontSizeF": 0.03886629992824683,
          "align": "left",
          "fill": "#878787",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "image",
          "id": "qr12",
          "label": "QR-код",
          "xf": 0.3159172446783066,
          "yf": 0.35991180546806095,
          "wf": 0.36815295383879454,
          "hf": 0.38786632228801815,
          "defaultSrc": "/layers/onix-main-qr.png",
          "opacity": 1
        }
      ]
    }
  ],
  "amfora": [
    {
      "id": "front",
      "widthPx": 170.08,
      "heightPx": 368.5,
      "widthMm": 60,
      "heightMm": 130,
      "layers": [
        {
          "kind": "image",
          "id": "deco17",
          "label": "Графика 1",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/amfora-front-deco1.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "text",
          "id": "t15",
          "text": "Оплата заказа.\nЧаевые. Отзыв.",
          "xf": 0.2114105126999059,
          "yf": 0.42189118046132973,
          "wf": 3,
          "fontSizeF": 0.08231420507996237,
          "align": "left",
          "fill": "#010202",
          "fontStyle": "bold",
          "rotation": 0
        },
        {
          "kind": "image",
          "id": "qr16",
          "label": "QR-код",
          "xf": 0.1666656867356538,
          "yf": 0.5388306648575305,
          "wf": 0.6667450611476952,
          "hf": 0.30773405698778833,
          "defaultSrc": "/layers/amfora-front-qr.png",
          "opacity": 1
        }
      ]
    }
  ],
  "rubikon-60": [
    {
      "id": "number",
      "widthPx": 170.08,
      "heightPx": 170.08,
      "widthMm": 60,
      "heightMm": 60,
      "layers": [
        {
          "kind": "image",
          "id": "deco19",
          "label": "Графика 1",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/rubikon-60-number-deco1.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "deco20",
          "label": "Графика 2",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/rubikon-60-number-deco2.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "deco21",
          "label": "Графика 3",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/rubikon-60-number-deco3.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "deco22",
          "label": "Графика 4",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/rubikon-60-number-deco4.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "deco23",
          "label": "Графика 5",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/rubikon-60-number-deco5.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "deco24",
          "label": "Графика 6",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/rubikon-60-number-deco6.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "text",
          "id": "t18",
          "text": "Оплата заказа.\nЧаевые.\nОтзыв.",
          "xf": 0.1700376293508937,
          "yf": 0.32365533866415797,
          "wf": 3,
          "fontSizeF": 0.09407337723424271,
          "align": "left",
          "fill": "#000000",
          "fontStyle": "bold",
          "rotation": 0
        }
      ]
    }
  ],
  "arktika": [
    {
      "id": "main",
      "widthPx": 170.08,
      "heightPx": 255.12,
      "widthMm": 60,
      "heightMm": 90,
      "layers": [
        {
          "kind": "image",
          "id": "deco29",
          "label": "Графика 1",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/arktika-main-deco1.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "text",
          "id": "t25",
          "text": "Оплата заказа.\nЧаевые. Отзыв.",
          "xf": 0.19066027751646283,
          "yf": 0.09358184383819376,
          "wf": 3,
          "fontSizeF": 0.08819379115710253,
          "align": "left",
          "fill": "#010202",
          "fontStyle": "bold",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t26",
          "text": "Оплатите заказ без официанта.\nЦеликом или только свою часть.",
          "xf": 0.16244473189087485,
          "yf": 0.24447162119786767,
          "wf": 3,
          "fontSizeF": 0.047036688617121354,
          "align": "left",
          "fill": "#010202",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t27",
          "text": "1234567- 01",
          "xf": 0.14957802210724364,
          "yf": 0.6492125274380685,
          "wf": 3,
          "fontSizeF": 0.035403927563499527,
          "align": "left",
          "fill": "#010202",
          "fontStyle": "normal",
          "rotation": -90
        },
        {
          "kind": "image",
          "id": "qr28",
          "label": "QR-код",
          "xf": 0.20833196142991534,
          "yf": 0.3677751646284102,
          "wf": 0.5832549388523047,
          "hf": 0.38883662590153656,
          "defaultSrc": "/layers/arktika-main-qr.png",
          "opacity": 1
        }
      ]
    }
  ],
  "naklejka-white": [
    {
      "id": "main",
      "widthPx": 226.77,
      "heightPx": 226.77,
      "widthMm": 80,
      "heightMm": 80,
      "layers": [
        {
          "kind": "image",
          "id": "deco35",
          "label": "Графика 1",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/naklejka-white-main-deco1.svg",
          "opacity": 0.3,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "deco36",
          "label": "Рамка",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/naklejka-white-main-deco2.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "text",
          "id": "t30",
          "text": "07",
          "xf": 0.7273056400758476,
          "yf": 0.44065793535300085,
          "wf": 3,
          "fontSizeF": 0.03527803501344975,
          "align": "left",
          "fill": "#878787",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t31",
          "text": "Оплата заказа.\nЧаевые. Отзыв.",
          "xf": 0.07875248048683688,
          "yf": 0.08596286986814836,
          "wf": 3,
          "fontSizeF": 0.09260484191030559,
          "align": "left",
          "fill": "#000000",
          "fontStyle": "bold",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t32",
          "text": "Оплатите заказ без\nофицианта. Целиком\nили только свою часть.",
          "xf": 0.08313533536182034,
          "yf": 0.702954976407814,
          "wf": 3,
          "fontSizeF": 0.03527803501344975,
          "align": "left",
          "fill": "#878787",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t33",
          "text": "1234567",
          "xf": 0.9556841733915421,
          "yf": 0.6186669312519292,
          "wf": 3,
          "fontSizeF": 0.022048771883406093,
          "align": "left",
          "fill": "#878787",
          "fontStyle": "normal",
          "rotation": 90
        },
        {
          "kind": "image",
          "id": "qr34",
          "label": "QR-код",
          "xf": 0.6137046346518499,
          "yf": 0.541025708868016,
          "wf": 0.27494818538607396,
          "hf": 0.27494818538607396,
          "defaultSrc": "/layers/naklejka-white-main-qr.png",
          "opacity": 1
        }
      ]
    }
  ],
  "naklejka-black": [
    {
      "id": "main",
      "widthPx": 226.77,
      "heightPx": 226.77,
      "widthMm": 80,
      "heightMm": 80,
      "layers": [
        {
          "kind": "image",
          "id": "deco42",
          "label": "Графика 1",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/naklejka-black-main-deco1.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "deco43",
          "label": "Рамка",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/naklejka-black-main-deco2.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "text",
          "id": "t37",
          "text": "07",
          "xf": 0.7277470564889535,
          "yf": 0.44065793535300085,
          "wf": 3,
          "fontSizeF": 0.03527803501344975,
          "align": "left",
          "fill": "#B3B2B2",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t38",
          "text": "Оплата заказа.\nЧаевые. Отзыв.",
          "xf": 0.07875248048683688,
          "yf": 0.08596286986814836,
          "wf": 3,
          "fontSizeF": 0.09260484191030559,
          "align": "left",
          "fill": "#FFFFFF",
          "fontStyle": "bold",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t39",
          "text": "Оплатите заказ без\nофицианта. Целиком\nили только свою часть.",
          "xf": 0.08313533536182034,
          "yf": 0.702954976407814,
          "wf": 3,
          "fontSizeF": 0.03527803501344975,
          "align": "left",
          "fill": "#B3B2B2",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t40",
          "text": "1234567",
          "xf": 0.9556841733915421,
          "yf": 0.6163703311725537,
          "wf": 3,
          "fontSizeF": 0.022048771883406093,
          "align": "left",
          "fill": "#B2B2B2",
          "fontStyle": "normal",
          "rotation": 90
        },
        {
          "kind": "image",
          "id": "qr41",
          "label": "QR-код",
          "xf": 0.6137046346518499,
          "yf": 0.541025708868016,
          "wf": 0.27494818538607396,
          "hf": 0.27494818538607396,
          "defaultSrc": "/layers/naklejka-black-main-qr.png",
          "opacity": 1
        }
      ]
    }
  ],
  "karelia": [
    {
      "id": "main",
      "widthPx": 238.11,
      "heightPx": 153.07,
      "widthMm": 84,
      "heightMm": 54,
      "layers": [
        {
          "kind": "image",
          "id": "deco49",
          "label": "Графика 1",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/karelia-main-deco1.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "deco50",
          "label": "Графика 2",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/karelia-main-deco2.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "text",
          "id": "t44",
          "text": "01",
          "xf": 0.2743257318046281,
          "yf": 0.14817665120533088,
          "wf": 3,
          "fontSizeF": 0.033597916929150394,
          "align": "left",
          "fill": "#000000",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t45",
          "text": "111222",
          "xf": 0.2461458989542648,
          "yf": 0.8062200300516104,
          "wf": 3,
          "fontSizeF": 0.020998698080718994,
          "align": "left",
          "fill": "#000000",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t46",
          "text": "Оплата заказа.\nЧаевые. Отзыв.",
          "xf": 0.5199143253118307,
          "yf": 0.3435493565035605,
          "wf": 3,
          "fontSizeF": 0.05039687539372559,
          "align": "left",
          "fill": "#000000",
          "fontStyle": "bold",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t47",
          "text": "Оплатите заказ без официанта.\nЦеликом или только свою часть.",
          "xf": 0.5195615471840745,
          "yf": 0.5700966877899001,
          "wf": 3,
          "fontSizeF": 0.025198437696862794,
          "align": "left",
          "fill": "#000000",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "image",
          "id": "qr48",
          "label": "QR-код",
          "xf": 0.1495506278610726,
          "yf": 0.27394590710132616,
          "wf": 0.28918399059258326,
          "hf": 0.44984386228522905,
          "defaultSrc": "/layers/karelia-main-qr.png",
          "opacity": 1
        }
      ]
    }
  ],
  "rubikon-50": [
    {
      "id": "logo",
      "widthPx": 141.73,
      "heightPx": 141.73,
      "widthMm": 50,
      "heightMm": 50,
      "layers": [
        {
          "kind": "image",
          "id": "deco51",
          "label": "Графика 1",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/rubikon-50-logo-deco1.svg",
          "opacity": 1,
          "decorative": true
        }
      ],
      "gridRow": 0,
      "gridCol": 1
    },
    {
      "id": "title",
      "widthPx": 141.73,
      "heightPx": 141.73,
      "widthMm": 50,
      "heightMm": 50,
      "layers": [
        {
          "kind": "text",
          "id": "t52",
          "text": "Меню.\nОплата заказа.\nЧаевые.",
          "xf": 0.3582163268185988,
          "yf": 0.3236618923304876,
          "wf": 0.85,
          "fontSizeF": 0.09405207083891907,
          "align": "left",
          "fill": "#1d1d1b",
          "fontStyle": "bold",
          "rotation": 0
        }
      ],
      "gridRow": 1,
      "gridCol": 0
    },
    {
      "id": "qr",
      "widthPx": 141.73,
      "heightPx": 141.73,
      "widthMm": 50,
      "heightMm": 50,
      "layers": [
        {
          "kind": "image",
          "id": "deco54",
          "label": "Графика 1",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/rubikon-50-qr-deco1.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "qr53",
          "label": "QR-код",
          "xf": 0.24998236082692446,
          "yf": 0.17942566852465958,
          "wf": 0.4938968461158541,
          "hf": 0.4938968461158541,
          "defaultSrc": "/layers/rubikon-50-qr-qr.png",
          "opacity": 1
        }
      ],
      "gridRow": 1,
      "gridCol": 1
    },
    {
      "id": "title2",
      "widthPx": 141.73,
      "heightPx": 141.73,
      "widthMm": 50,
      "heightMm": 50,
      "layers": [
        {
          "kind": "text",
          "id": "t55",
          "text": "Меню.\nОплата заказа.\nЧаевые.",
          "xf": 0.3582163268185988,
          "yf": 0.3236618923304876,
          "wf": 0.85,
          "fontSizeF": 0.09405207083891907,
          "align": "left",
          "fill": "#1d1d1b",
          "fontStyle": "bold",
          "rotation": 0
        }
      ],
      "gridRow": 1,
      "gridCol": 2
    },
    {
      "id": "qr2",
      "widthPx": 141.73,
      "heightPx": 141.73,
      "widthMm": 50,
      "heightMm": 50,
      "layers": [
        {
          "kind": "image",
          "id": "deco57",
          "label": "Графика 1",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/rubikon-50-qr2-deco1.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "image",
          "id": "qr56",
          "label": "QR-код",
          "xf": 0.24998236082692446,
          "yf": 0.17942566852465958,
          "wf": 0.4938968461158541,
          "hf": 0.4938968461158541,
          "defaultSrc": "/layers/rubikon-50-qr2-qr.png",
          "opacity": 1
        }
      ],
      "gridRow": 1,
      "gridCol": 3
    },
    {
      "id": "number",
      "widthPx": 141.73,
      "heightPx": 141.73,
      "widthMm": 50,
      "heightMm": 50,
      "layers": [
        {
          "kind": "image",
          "id": "deco60",
          "label": "Графика 1",
          "xf": 0,
          "yf": 0,
          "wf": 1,
          "hf": 1,
          "defaultSrc": "/layers/rubikon-50-number-deco1.svg",
          "opacity": 1,
          "decorative": true
        },
        {
          "kind": "text",
          "id": "t58",
          "text": "01",
          "xf": 0.47117759119452485,
          "yf": 0.3707048613560997,
          "wf": 0.85,
          "fontSizeF": 0.07055669230226487,
          "align": "left",
          "fill": "#000000",
          "fontStyle": "normal",
          "rotation": 0
        },
        {
          "kind": "text",
          "id": "t59",
          "text": "1234567",
          "xf": 0.39688139420023993,
          "yf": 0.541804840189092,
          "wf": 0.85,
          "fontSizeF": 0.07055669230226487,
          "align": "left",
          "fill": "#000000",
          "fontStyle": "normal",
          "rotation": 0
        }
      ],
      "gridRow": 2,
      "gridCol": 1
    }
  ]
};
